#!/usr/bin/env bash

test -d /project/dev || {
 echo -e "\033[31mCould not find the dev directory; are you sharing it with this container?\033[0m"
 echo ''
 echo -e "Usage: \033[32mdocker run --rm -v \$(pwd):/project\033[0m"
 echo -e "Run this from the root directory of this repository."
 exit 1
}

# The list of the files to source for the shell functions, one per line, curated list.
files="dev/test/tests.php
dev/setup/src/colors.php
dev/setup/src/nightly.php
dev/setup/src/plugins.php
dev/setup/src/process.php
dev/setup/src/pue.php
dev/setup/src/utils.php
dev/setup/docker.php
dev/setup/shell.php
dev/setup/wordpress.php
"

# Create the shell functions header.
echo "<?php
/**
 * Global namespace functions.
 *
 * This file is auto-generated by the dev/setup/shell-stubs.sh script.
 */

" > dev/setup/php-shell-functions.php

# Stub each file.
echo "${files}" | xargs -I _file_ stub-file.sh _file_

# Append the shell header.
echo "
echo implode( PHP_EOL, [
	'...the Modern Tribe version.',
	PHP_EOL,
	'You will be able to use any of the functions defined in the repository files.',
	'This is a modified PHP interactive shell, <light_cyan>auto-completion is available.',
	PHP_EOL
] );
" >> dev/setup/php-shell-functions.php

# Lint the result.
php -l dev/setup/php-shell-functions.php
