name: Activation test

on:
  # Run on push.
  - push
  # Run once a day.
  # schedule: '* 0 * * *'

jobs:
  build:
    strategy:
      matrix:
        wordpress: [ "5.3" ]
    name: Test activation on WP ${{ matrix.wordpress }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull the plugins (last 3 versions)
        run: php dev/setup/dl-plugin-zips.php 3 the-events-calendar,event-tickets,tribe-filterbar,event-tickets-plus
        env:
          EVENTS_CALENDAR_PRO_LICENSE: ${{ secrets.EVENTS_CALENDAR_PRO_LICENSE }}
          EVENT_TICKETS_PLUS_LICENSE: ${{ secrets.EVENT_TICKETS_PLUS_LICENSE }}
          COMMUNITY_EVENTS_LICENSE: ${{ secrets.COMMUNITY_EVENTS_LICENSE }}
          COMMUNITY_TICKETS_LICENSE: ${{ secrets.COMMUNITY_TICKETS_LICENSE }}
          EVENTBRITE_TICKETS_LICENSE: ${{ secrets.EVENTBRITE_TICKETS_LICENSE }}
          EVENT_AGGREGATOR_LICENSE: ${{ secrets.EVENT_AGGREGATOR_LICENSE }}
          FILTERBAR_LICENSE: ${{ secrets.FILTERBAR_LICENSE }}
          IMAGE_WIDGET_PLUS_LICENSE: ${{ secrets.IMAGE_WIDGET_PLUS_LICENSE }}
          PUE_URL: ${{ secrets.PUE_URL }}
          PUE_SIGNED_SECRET: ${{ secrets.PUE_SIGNED_SECRET }}
      - name: Randomly activate plugins (3 epochs, last 3 WP versions)
        run: php dev/randomly-activate-plugins.php 3 3
