name: Activation test

on:
  # Run on push.
  - push
  # Run once a day.
  # schedule: '* 0 * * *'

jobs:
  build:
    env:
      EPOCHS: 10
      WP_NUMBER_VERSIONS: 3
      PLUGINS_NUMBER_VERSIONS: 3
    name: Test random activation
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull latest WordPress container version
        run: docker pull wordpress:latest

      - name: Set today date
        run: echo "::set-env name=TODAY_DATE::$(.github/workflows/today_date.sh)"


      - name: Restore plugin store from cache
        uses: gerbal/always-cache@v1.0.3
        with:
          path: dev/test/_plugin_store
          key: ${{ env.TODAY_DATE }}-${{ hashFiles('.github/workflows/activation-test-plugins') }}-${{ env.PLUGINS_NUMBER_VERSIONS }}-plugin-store

      - name: Pull the plugins
        run: test -d dev/test/_plugin_store || php dev/setup/dl-plugin-zips.php ${{ env.PLUGINS_NUMBER_VERSIONS }} "$(<.github/workflows/activation-test-plugins)"
        env:
          EVENTS_CALENDAR_PRO_LICENSE: ${{ secrets.EVENTS_CALENDAR_PRO_LICENSE }}
          EVENT_TICKETS_PLUS_LICENSE: ${{ secrets.EVENT_TICKETS_PLUS_LICENSE }}
          COMMUNITY_EVENTS_LICENSE: ${{ secrets.COMMUNITY_EVENTS_LICENSE }}
          COMMUNITY_TICKETS_LICENSE: ${{ secrets.COMMUNITY_TICKETS_LICENSE }}
          EVENTBRITE_TICKETS_LICENSE: ${{ secrets.EVENTBRITE_TICKETS_LICENSE }}
          EVENT_AGGREGATOR_LICENSE: ${{ secrets.EVENT_AGGREGATOR_LICENSE }}
          FILTERBAR_LICENSE: ${{ secrets.FILTERBAR_LICENSE }}
          IMAGE_WIDGET_PLUS_LICENSE: ${{ secrets.IMAGE_WIDGET_PLUS_LICENSE }}
          PUE_URL: ${{ secrets.PUE_URL }}
          PUE_SIGNED_SECRET: ${{ secrets.PUE_SIGNED_SECRET }}

      - name: Randomly activate plugins
        run: php dev/randomly-activate-plugins.php ${{ env.EPOCHS }} ${{ env.WP_NUMBER_VERSIONS }}
